version: "3"
services:
  web:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mysql

  mysql:
    image: "mysql"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: test1234
      MYSQL_DATABASE: node_app
    ports:
      - 3306:3306
          
